# Pull base image.
FROM rons/java

MAINTAINER ron.smits@gmail.com
WORKDIR /opt

RUN wget http://dl.bintray.com/gitblit/releases/gitblit-1.5.1.tar.gz
RUN tar xzf gitblit-1.5.1.tar.gz
# CMD ["/usr/bin/supervisord"]
